import Head from 'next/head'


export default function Home() {

  return (
    <>
      <Head>
        <title>HF-Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='p-[5%]'>
      <h1 className='text-center text-black'>HF-Tracker</h1>
      </main>
    </>
  )
}
